# Goal:

## ID of the model to move.
string id

## The trajectory to move the model along to. The headers' stamps defines the time at which each
## pose shall be reached. The detail how to resolve the time stamp to the simulation time is defined
## according to the time resolution mode set The frame_ids are ignored, all coordinates are in the
## simulation frame.
geometry_msgs/PoseStamped[] trajectory

# the time of the timepoint is already defined in sim time
uint8 TIME_RESOLUTION_MODE_SIM_TIME = 0
# the time of the timepoint is defined relative to the arrival of the message
uint8 TIME_RESOLUTION_MODE_RELATIVE_SIM_TIME = 1
uint8 time_resolution_mode 0

## Number of iterations. Repeat indefinitely if set to the maximum possible value.
uint32 ITERATIONS_INFINITE = 4294967295
uint32 iterations 1

uint8 COLLISION_MODE_IGNORE = 0
uint8 COLLISION_MODE_PAUSE = 1
uint8 COLLISION_MODE_ABORT = 2
uint8 collision_mode 0

uint8 INTERPOLATION_MODE_LINEAR = 0
uint8 INTERPOLATION_MODE_CUBIC_SPLINE = 1
uint8 interpolation_mode 0
---
# Result:

uint8 STATUS_SUCCESS = 0
uint8 STATUS_CANCELED = 1
uint8 STATUS_INVALID_ID = 2
uint8 STATUS_INVALID_TRAJECTORY = 3
uint8 STATUS_OVERLAPPING_TRAJECTORY = 4
uint8 STATUS_INVALID_VALUE = 5
uint8 STATUS_IN_COLLISION = 6
uint8 status
---
# Feedback:

## Number of current iteration, starting from 0.
uint32 iteration

## Index of reached trajectory element.
uint32 trajectory_index
